name: ESLint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: ESLint (Node v16)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --force

      - name: Pre-fix ESLint
        run: npm run lint:fix
        
      - name: Run ESLint
        run: npm run lint

      - name: Run TSC
        run: npm run build:check